COLUMNS_NAME_ETAT_STOCK = [
    "SDU_CENTRAL",
    "DMM_CENTRAL",
    "MSD_CENTRAL",
    "STATUT_CENTRAL",
    "CONSO_DECENTRALISE",
    "SDU_DECENTRALISE",
    "CMM_DECENTRALISE",
    "MSD_DECENTRALISE",
    "STATUT_DECENTRALISE",
    "nombre_de_site_en_rupture_annexe_2",
    "SDU_NATIONAL",
    "CMM_NATIONAL",
    "MSD_NATIONAL",
    "STATUT_NATIONAL",
    "Date de Péremption la plus proche (BRUTE)",
    "Date de Péremption la plus proche",
    "Quantité correspondante",
    "MSD correspondant",
    "Qtité attendue Annexe 2",
    "MSD attendu Annexe 2",
    "Qtité réceptionnés non en Stock Annexe 2",
    "MSD reçu Annexe 2",
    "Financement Annexe 2",
    "Date Probable de Livraison Annexe 2",
    "Date Effective de Livraison Annexe 2",
    "Delivery status Annexe 2",
    "Analyse du risque / Commentaires Annexe 2",
    "Diligences au niveau Central Annexe 2",
    "Diligences au niveau périphérique Annexe 2",
    "Responsable Annexe 2",
    "Dilig. Choisie Annexe 2",
]


DICO_COLUMNS = {
    "Distribution effectuée": "distribution_effectuee",
    "Quantité reçue entrée en stock": "quantite_recue_stock",
    "Quantité de PPI": "quantite_ppi",
    "Quantité prélévée en Contrôle Qualité (CQ)": "quantite_prelevee_cq",
    "Ajustement de stock": "ajustement_stock",
    "Stock Théorique Final SAGE": "stock_theorique_final_sage",
    "Stock Théorique Final Attendu": "stock_theorique_final_attendu",
    "ECARTS": "ecarts",
    "Justification des écarts": "justification_ecarts",
    "Diligences": "diligences",
    "SDU_CENTRAL": "sdu_central_annexe_2",
    "DMM_CENTRAL": "dmm_central_annexe_2",
    "MSD_CENTRAL": "msd_central_annexe_2",
    "STATUT_CENTRAL": "statut_central_annexe_2",
    "CONSO_DECENTRALISE": "conso_decentralise_annexe_2",
    "SDU_DECENTRALISE": "sdu_decentralise_annexe_2",
    "CMM_DECENTRALISE": "cmm_decentralise_annexe_2",
    "MSD_DECENTRALISE": "msd_decentralise_annexe_2",
    "STATUT_DECENTRALISE": "statut_decentralise_annexe_2",
    "SDU_NATIONAL": "sdu_national_annexe_2",
    "CMM_NATIONAL": "cmm_national_annexe_2",
    "MSD_NATIONAL": "msd_national_annexe_2",
    "STATUT_NATIONAL": "statut_national_annexe_2",
    "Date de Péremption la plus proche (BRUTE)": "date_peremption_plus_proche_brute_annexe_2",
    "Date de Péremption la plus proche": "date_peremption_plus_proche_annexe_2",
    "Quantité correspondante": "quantite_correspondante_annexe_2",
    "MSD correspondant": "msd_correspondant_annexe_2",
    "Qtité attendue Annexe 2": "quantite_attendue_annexe_2",
    "MSD attendu Annexe 2": "msd_attendu_annexe_2",
    "Qtité réceptionnés non en Stock Annexe 2": "quantite_non_stockee_annexe_2",
    "MSD reçu Annexe 2": "msd_recu_annexe_2",
    "Financement Annexe 2": "financement_annexe_2",
    "Date Probable de Livraison Annexe 2": "date_probable_livraison_annexe_2",
    "Date Effective de Livraison Annexe 2": "date_effective_livraison_annexe_2",
    "Delivery status Annexe 2": "statut_annexe_2",
    "Analyse du risque / Commentaires Annexe 2": "analyse_risque_commentaires_annexe_2",
    "Diligences au niveau Central Annexe 2": "diligences_central_annexe_2",
    "Diligences au niveau périphérique Annexe 2": "diligences_peripherique_annexe_2",
    "Responsable Annexe 2": "responsable_annexe_2",
    "Dilig. Choisie Annexe 2": "dilig_choisie_annexe_2",
}
