name: Push update_stock_file_tracking_data

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/push_update_stock_file_tracking_data.yaml"
      - "update_stock_file_tracking_data/**"
      - "!update_stock_file_tracking_data/docs/**"
      - "!update_stock_file_tracking_data/README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: Configure OpenHEXA CLI
        uses: blsq/openhexa-cli-action@v1
        with:
          workspace: "workspace-civ-msp-12508c"
          token: ${{ secrets.OH_TOKEN }}

      - name: Push pipeline to OpenHEXA
        run: |
          openhexa pipelines push update_stock_file_tracking_data \
            --code "update-stock-file-tracking-data" \
            --description "${{ github.event.head_commit.message }}" \
            --link "https://github.com/aanoble/logistics-stocks/commit/${{ github.sha }}" \
            --yes
